/**
 * Created by admin on 2016/12/19.
 */
window.onload=function(){
    (function(){
        setTimeout(function(){
            showAnimation($('.core'),function(){
                heightAnimation($('.line-top07'),298,149,function(){
                    showAnimation($('.core-tb'));
                    widthAnimation($('.first-w'),160,80);
                    setTimeout(function(){
                        heightAnimation($('.line-top00'),290,145,function(){
                            widthAnimation($('.left-line-top01'),192,96,function(){
                                showAnimation($('.left-top'));
                                widthAnimation( $('.left-line-top02'),132,66,function(){
                                    heightAnimation($('.line-top01'),104,52);
                                    widthAnimation( $('.left-line-top03'),176,88,function(){
                                        heightAnimation($('.line-top02'),44,22,function(){
                                            widthAnimation($('.left-line-top04'),684,342,function(){
                                                heightAnimation($('.line-top03'),80,40,function(){
                                                    showAnimation($('.first-top'));
                                                });
                                                heightAnimation($('.line-top04'),80,40);
                                                heightAnimation($('.line-top05'),80,40);
                                                heightAnimation($('.line-bottom01'),80,38);
                                                heightAnimation($('.line-bottom02'),80,38);
                                                heightAnimation($('.line-bottom03'),80,38);
                                            });
                                            widthAnimation($('.left-line-top05'),684,342);
                                        });
                                        heightAnimation($('.line-bottom00'),44,22);
                                    });
                                });
                            });
                        });
                        heightAnimation($('.line-top08'),160,82,function(){
                            widthAnimation($('.right-line-top01'),192,96,function(){
                                showAnimation($('.right-top'));
                                widthAnimation($('.right-line-top02'),1008,504,function(){
                                    heightAnimation($('.line-top09'),164,82,function(){
                                        showAnimation($('.right04'));
                                        showAnimation($('.right05'));
                                        showAnimation($('.right06'));
                                        widthAnimation($('.right-line-top03'),118,59,function(){
                                            heightAnimation($('.line-top10'),284,142,function(){
                                                showAnimation($('.right01'));
                                                showAnimation($('.right02'));
                                                showAnimation($('.right03'));
                                            });
                                            heightAnimation($('.line-top12'),284,142);
                                            heightAnimation($('.line-top14'),284,142);
                                        });
                                        widthAnimation($('.right-line-top04'),118,59);
                                        widthAnimation($('.right-line-top05'),118,59);
                                    });
                                    heightAnimation($('.line-top11'),164,82);
                                    heightAnimation($('.line-top13'),164,82);
                                });
                            });
                        });
                        heightAnimation($('.line-bottom05'),296,148,function(){
                            widthAnimation($('.left-line-bottom01'),192,96,function(){
                                showAnimation($('.left-bottom'));
                                widthAnimation($('.left-line-bottom02'),1002,501,function(){
                                    heightAnimation($('.line-bottom06'),226,113,function(){
                                        showAnimation($('.left11'));
                                        showAnimation($('.left12'));
                                        showAnimation($('.left13'));
                                        widthAnimation($('.left-line-bottom03'),116,58,function(){
                                            heightAnimation($('.line-bottom09'),274,137,function(){
                                                showAnimation($('.left14'));
                                                showAnimation($('.left15'));
                                                showAnimation($('.left16'));
                                            });
                                            heightAnimation($('.line-bottom10'),274,137);
                                            heightAnimation($('.line-bottom11'),274,137);
                                        });
                                        widthAnimation($('.left-line-bottom04'),116,58);
                                        widthAnimation($('.left-line-bottom05'),116,58);
                                    });
                                    heightAnimation($('.line-bottom07'),226,113);
                                    heightAnimation($('.line-bottom08'),226,113);
                                });
                            });
                        });
                        heightAnimation($('.line-bottom13'),102,51,function(){
                            widthAnimation($('.right-line-middle01'),146,73,function(){
                                showAnimation($('.right'));
                                widthAnimation($('.right-line-middle02'),140,70,function(){
                                    heightAnimation($('.line-top15'),180,90,function(){
                                        widthAnimation($('.right-line-middle03'),160,80,function(){
                                            showAnimation($('.right07'));
                                            widthAnimation($('.right-line-middle04'),248,124,function(){
                                                showAnimation($('.right08'));
                                            });
                                        })
                                    });
                                    heightAnimation($('.line-bottom14'),114,57,function(){
                                        widthAnimation($('.right-line-middle05'),160,80,function(){
                                            showAnimation($('.right09'));
                                            widthAnimation($('.right-line-middle06'),248,124,function(){
                                                showAnimation($('.right10'));
                                            });
                                        })
                                    });
                                });
                            });
                        });
                        heightAnimation($('.line-bottom15'),350,175,function(){
                            widthAnimation($('.right-line-bottom01'),238,119,function(){
                                showAnimation($('.right-bottom'));
                                widthAnimation($('.right-line-bottom02'),136,68,function(){
                                    heightAnimation($('.line-bottom16'),108,54,function(){
                                        widthAnimation($('.right-line-bottom03'),136,68,function(){
                                            heightAnimation($('.line-top16'),48,24,function(){
                                                widthAnimation($('.right-line-bottom04'),724,362,function(){
                                                    heightAnimation($('.line-top17'),82,41,function(){
                                                        showAnimation($('.right11'));
                                                        showAnimation($('.right12'));
                                                        showAnimation($('.right13'));
                                                    });
                                                    heightAnimation($('.line-top18'),82,41);
                                                    heightAnimation($('.line-top19'),82,41);
                                                });
                                            });
                                            heightAnimation($('.line-bottom17'),48,24,function(){
                                                widthAnimation($('.right-line-bottom05'),724,362,function(){
                                                    heightAnimation($('.line-bottom18'),66,33,function(){
                                                        showAnimation($('.right14'));
                                                        showAnimation($('.right15'));
                                                        showAnimation($('.right16'));
                                                    });
                                                    heightAnimation($('.line-bottom19'),66,33);
                                                    heightAnimation($('.line-bottom20'),66,33);
                                                });
                                            });
                                        });
                                    });
                                });
                            })
                        });
                    },160);
                    widthAnimation($('.left-line'),290,145,function(){
                        showAnimation($('.left'));
                        widthAnimation($('.left-line-middle'),136,68,function(){
                            heightAnimation($('.line-top06'),118,59,function(){
                                widthAnimation($('.left-line-middle01'),156,78,function(){
                                    showAnimation($('.left08'));
                                    widthAnimation($('.left-line-middle02'),248,124,function(){
                                        showAnimation($('.left07'));
                                    });
                                });
                            });
                            heightAnimation($('.line-bottom04'),232,116,function(){
                                widthAnimation($('.left-line-middle03'),156,78,function(){
                                    showAnimation($('.left09'));
                                    widthAnimation($('.left-line-middle04'),248,124,function(){
                                        showAnimation($('.left10'));
                                    });
                                });
                            });
                        });
                    });
                });
                heightAnimation($('.line-bottom12'),290,154);
            });
        },500);
        function showAnimation(obj,fun){
            obj.addClass('show-icon').show();
            if(fun){
                fun();
            }
        }
        function widthAnimation(obj,time,number,fun){
            obj.css({'display':'block','width':0}).animate({'width':number+'px'},time,function(){
                if(fun){
                    fun();
                }
            });
        }
        function heightAnimation(obj,time,number,fun){
            obj.css({'display':'block','height':0}).animate({'height':number+'px'},time,function(){
                if(fun){
                    fun();
                }
            });
        }
    })();
};